--- 
title: "CH3/40227 Advanced Spectroscopic Techniques"
author: "Fiona Dickinson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: chemfd/CH3040227
description: "Advanced Spectroscopic Techniques"
---

# CH3/40227 Advanced Spectroscopic Techniques {-}

## Welcome & Preliminary Infomation {-}

Welcome to the coursepage for CH30227 & CH40227 Advanced Spectroscopic Techniques. The notes have been prepared in a package called BookDown for RStudio so that the equations are accessible to screen readers. However, by providing the notes as a .html webpage I can also embed short videos to further describe some of the topics. Further you can download the material in a format that suits you (either pdf or epub) to view offline, or change the way this document appears for ease of reading.

The course is entirely taught by Dr Fiona Dickinson.



### Prerequisite knowledge {-}

The course relies extensively on concepts from CH30129 (or CH30217) Photochemistry as well as material from the spectroscopy section of CH10137/8, and the quantum mechanics of CH20151/2. However more generic skills, such as experiment planning, and drawing conclusions on data will form an important strand to this course. 

### Assessment for this course {-}

The course is assessed by a '1 hour' exam, this is to say it should take an hour to complete, exam details will be shared centrally later in the semester.

The exam format will contain 2 x 25 mark questions. The questions will likely contain two or more of the following: data to examine, description of a spectrometer or spectrometer component, and design of experiments.

### Feedback for this course {-}

Much of the work will be peer based in small groups, and you will provide feedback to each other. In wrapping up these discussions I will also provide feedback to discussions.

I appreciate your understanding that feedback may be delayed during these uncertain times as I have childcare responsibilities.

I will not provide model answers for past exam questions, this is because there will be multiple ways in which marks may be achieved. Instead I will happily provide feedback on your attempts at past papers. All I ask is:

- papers are received in good time
- when you attempt papers you try and replicate the exam conditions (i.e. do it alone, in one sitting in a limited period)
- you do not submit more than one past paper at a time (I am happy to go through more than one feedback cycle, but want you to reflect on the feedback you have received)
- you highlight sections where you particularly want feedback
- you provide the file as a .pdf, with the file name containing your username, the year of paper attempted and the unit code
- please space out work enough so that I can write feedback

## Week 1 tasks {-}

I set a number of week 1 tasks.

- For the 'spectrometer components document' on Teams, please divide the work between you, and write a few sentences (and include figures if relevant) for your chosen component(s). This is a shared document and is hosted on Teams because I can't work out how to do it on Moodle... (the CH40227 class will act as editors to this body or work).

- Think about the spectroscopic techniques you have used previously (you should all have used at least one of UV/vis, IR and fluorescence), think about what components may have been in the 'beige box' and how these differ between different spectrometers...

- Remember to let me know if you want particular groups in the zoom chat (CH30227 only)


## Report errors {-}

If you spot any errors, please message me in Teams or (if this works), report on the error log below

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSc83b-C0FsgDr5eQxvT-2NWwEtvOEwYU1WbLE4j53wWfUDIXQ/viewform?embedded=true" width="640" height="1242" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>




## Edit log {-}

Typos fixed (end of section 1.1.2 for clarity, section 2.3 for bad coding of links) 160221
Chapter 3 started 240221
Chapters 1 & 2 130221
Initial commit 010221
